version: 2
enable-beta-ecosystems: true #Needed for pub support
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/builder/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/example/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "weekly"
