name: flutter_web_bluetooth_builder
description: Code generation for data retrieved from the web

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  analyzer: ^8.2.0
  args: ^2.7.0
  build: ^3.0.2
  code_builder: ^4.10.1
  dart_style: ^3.1.2
  http: ^1.5.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3
