name: flutter_web_bluetooth_builder
description: Code generation for data retrieved from the web

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^7.4.2
  args: ^2.7.0
  build: ^2.4.2
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  http: ^1.3.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3
