name: flutter_web_bluetooth_builder
description: Code generation for data retrieved from the web

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: '>=6.11.0 <8.0.0'
  args: ^2.6.0
  build: ^2.4.1
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  http: ^1.2.2
  path: ^1.9.1
  pub_semver: ^2.1.5
  yaml: ^3.1.2
