name: Run CI
on:
  push:
    paths:
      - lib/**
      - test/**
      - pubspec.yaml
      - pubspec.lock
      - .github/workflows/run_ci.yml
      - example/lib/**
      - example/test/**
      - example/pubspec.yaml
      - example/pubspec.lock
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        flutter: [ stable, beta ]
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
      - run: flutter --version

      - name: Restore packages
        run: |
          dart pub get
          cd builder
          dart pub get
          cd ../

      - name: Analyze
        run: dart analyze

      - name: Formatted
        run: dart format --set-exit-if-changed .

      - name: Run tests ubuntu + macos
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: dart test ./test
      - name: Run tests windows
        if: matrix.os == 'windows-latest'
        run: dart test -c vm:kernel,dart2js ./test
